### ISSUE TITLE
problem run in pycharm

### ISSUE THREAD

**Issue by hany-dev** [yasirroni/matpower-pip#12]
I run the demo in pycharm and this problem will occur,

```text
D:\work_software\anacoda\python.exe D:\work_code\optimization\project1\main.py 
Traceback (most recent call last):
  File "D:\work_code\optimization\project1\main.py", line 8, in <module>
    from matpower import start_instance
  File "D:\work_software\anacoda\Lib\site-packages\matpower\__init__.py", line 179, in <module>
    version_line = open(os.path.join(current_path, 'CHANGES.md'), "rt").read()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 119265: illegal multibyte sequence
```

**Comment by yasirroni** [comment]
1. How do you install matpower-pip?
2. Can you try to install it without conda?

**Comment by hany-dev** [comment]
I install the matpower through pip by running the command "pip install matpower" .  I try to run the instance without the pycharm or conda. It turns out the same result.  By the way, the software is run in the Windows environment.

**Comment by yasirroni** [comment]
Can you help me open `File "D:\work_software\anacoda\Lib\site-packages\matpower\__init__.py", line 179` thath contains

```
version_line = open(os.path.join(current_path, 'CHANGES.md'), "rt").read()
```

into

```
with open(os.path.join(current_path, 'CHANGES.md'), "rt", encoding="utf-8") as file:
    version_line = file.read()
```
___
This part of code https://github.com/yasirroni/matpower-pip/blob/db2224ec4711c71959276002205a1b4902fc0b15/matpowerpip/__init__.py#L179

**Comment by yasirroni** [comment]
Also, can you help me run this script?

```python
import locale

# Get the default encoding
default_encoding = locale.getpreferredencoding(False)
print(f"Default Encoding: {default_encoding}")
```

**Comment by hany-dev** [comment]
I change the code at the line 179, and luckily , the error are gone. I run the script and here is the result 

Default Encoding: cp936

But, I found another error , I run the demo code here.
    m = start_instance()
    m.runpf()
the result is 
Traceback (most recent call last):
  File "D:\work_software\anacoda\Lib\site-packages\matpower\__init__.py", line 60, in start_session
    from oct2py import Oct2Py
ModuleNotFoundError: No module named 'oct2py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work_code\optimization\project1\main.py", line 159, in <module>
    m = start_instance()
        ^^^^^^^^^^^^^^^^
  File "D:\work_software\anacoda\Lib\site-packages\matpower\__init__.py", line 40, in start_instance
    m = start_session(engine=engine)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work_software\anacoda\Lib\site-packages\matpower\__init__.py", line 65, in start_session
    raise ImportError(msg)
ImportError: No package named Oct2Py. Please install using `pip install matpower[octave]` or `pip install oct2py`.


So I install the oct2py , and the error changed
But there is still some error
![image](https://github.com/yasirroni/matpower-pip/assets/39269298/59e38d7e-1d66-4d39-8f3c-3823af97750b)
![image](https://github.com/yasirroni/matpower-pip/assets/39269298/0169277f-ffef-4447-ad6e-98d3f3051160)

**Comment by yasirroni** [comment]
Please use markdown highlighting and code block using triplle `.

**Comment by yasirroni** [comment]
Read installation tutorial for Oct2Py and Octave at mypower tutorial [here](https://github.com/yasirroni/mypower/blob/master/README_INSTALL_OCTAVE_AND_OCT2PY.md)

I would suggest installing Octave first, restart computer, oct2py, restart computer, and check if installation successful or not.

**Comment by yasirroni** [comment]
If you want to get a more direct online support, you can hire me via [ko-fi](https://ko-fi.com/yasirroni/commissions#buyShopCommissionModal) or [upwork](https://www.upwork.com/freelancers/~01c65f612ef9512e33?viewMode=1). You also can reach me on [linkedin](https://www.linkedin.com/in/yasirroni/)
