### ISSUE TITLE
No package named Oct2Py in Mac.

### ISSUE THREAD

**Issue by 1rashiid** [yasirroni/matpower-pip#16]
I get the following error. 

"ImportError: No package named Oct2Py. Please install using `pip install matpower[octave]` or `pip install oct2py`."

I tried a different way to install oct2py and it does not work. You have a solution for Windows on your website, but I can not see any hint for Mac. Could you please help me with that? Thank you.

**Comment by yasirroni** [comment]
@1rashiid Do you have octave installed? Check via `octave` in terminal and send here the output.

**Comment by 1rashiid** [comment]
@yasirroni Yes. I have the octave. I can install the package, but I get that error when I want to run the ACOPF on my data. So, honestly, I did not get what I should run in my terminal to check the output. Do you mean, I should run all of my code in the octave terminal?

**Comment by yasirroni** [comment]
Please read before reply. `octave` cli on terminal.

**Comment by 1rashiid** [comment]
Thank you for getting back to me. Yes, I have the octave and here is the terminal output and a test.
![Screenshot 2024-06-03 at 8 05 53 AM](https://github.com/yasirroni/matpower-pip/assets/77123453/6c5cdca1-9898-45d0-aeef-7d5386f33c7c)

**Comment by yasirroni** [comment]
`!pip install matpower oct2py` should solve your problem if you already have octave cli, preferably octave 9.

**Comment by 1rashiid** [comment]
Ok. I have the octave and I already tested all of the commands such as `pip install ...` and `python3 -m pip...` and it does not work. Btw, thanks for your time.

**Comment by yasirroni** [comment]
@1rashiid What is the output of the terminal? Please always copy paste and use code fence when asking in GitHub.
