### ISSUE TITLE
`Oct2PyError: Octave evaluation error: error: save: error while writing '' to MAT file`

### ISSUE THREAD

**Issue by chiru7187** [yasirroni/matpower-pip#2]
**for this below code** 

```python
mpc = matpower.eval('case9', verbose=False)

mpc = matpower.runopf(mpc)
```

**Result is** 
```plaintext
MATPOWER Version 7.1, 08-Oct-2020 -- AC Optimal Power Flow
  AC OPF formulation: polar voltages, power balance eqns
MATPOWER Interior Point Solver -- MIPS, Version 1.4, 08-Oct-2020
 (using built-in linear solver)
Converged!

Converged in 0.12 seconds
Objective Function Value = 5296.69 $/hr
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses              9     Total Gen Capacity     820.0        -900.0 to 900.0
Generators         3     On-line Capacity       820.0        -900.0 to 900.0
Committed Gens     3     Generation (actual)    318.3              -9.6
Loads              3     Load                   315.0             115.0
  Fixed            3       Fixed                315.0             115.0
  Dispatchable     0       Dispatchable          -0.0 of -0.0      -0.0
Shunts             0     Shunt (inj)             -0.0               0.0
Branches           9     Losses (I^2 * Z)         3.31             36.46
Transformers       0     Branch Charging (inj)     -              161.1
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   1.072 p.u. @ bus 9          1.100 p.u. @ bus 8
Voltage Angle      -4.62 deg   @ bus 9          4.89 deg   @ bus 2
P Losses (I^2*R)             -                  1.39 MW    @ line 8-9
Q Losses (I^2*X)             -                  9.36 MVAr  @ line 8-2
Lambda P           24.03 $/MWh @ bus 2         25.00 $/MWh @ bus 9
Lambda Q           -0.00 $/MWh @ bus 3          0.11 $/MWh @ bus 9

================================================================================
|     Bus Data                                                                 |
================================================================================
 Bus      Voltage          Generation             Load          Lambda($/MVA-hr)
  #   Mag(pu) Ang(deg)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)     P        Q
----- ------- --------  --------  --------  --------  --------  -------  -------
    1  1.100    0.000*    89.80     12.94       -         -      24.756     -
    2  1.097    4.893    134.32      0.05       -         -      24.035     -
    3  1.087    3.249     94.19    -22.62       -         -      24.076     -
    4  1.094   -2.463       -         -         -         -      24.756   0.004
    5  1.084   -3.982       -         -       90.00     30.00    24.998   0.027
    6  1.100    0.602       -         -         -         -      24.076     -
    7  1.089   -1.197       -         -      100.00     35.00    24.254   0.036
    8  1.100    0.905       -         -         -         -      24.035     -
    9  1.072   -4.616       -         -      125.00     50.00    24.999   0.112
                        --------  --------  --------  --------
               Total:    318.31     -9.63    315.00    115.00

================================================================================
|     Branch Data                                                              |
================================================================================
Brnch   From   To    From Bus Injection   To Bus Injection     Loss (I^2 * Z)
  #     Bus    Bus    P (MW)   Q (MVAr)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
-----  -----  -----  --------  --------  --------  --------  --------  --------
   1      1      4     89.80     12.94    -89.80     -9.02     0.000      3.92
   2      4      5     35.22     -3.90    -35.04    -13.87     0.181      0.98
   3      5      6    -54.96    -16.13     55.97    -22.18     1.010      4.40
   4      3      6     94.19    -22.62    -94.19     27.28     0.000      4.66
   5      6      7     38.22     -5.10    -38.07    -18.68     0.149      1.26
   6      7      8    -61.93    -16.32     62.21      0.82     0.279      2.36
   7      8      2   -134.32      9.32    134.32      0.05     0.000      9.36
   8      8      9     72.11    -10.14    -70.72    -18.94     1.394      7.01
   9      9      4    -54.28    -31.06     54.58     12.92     0.295      2.51
                                                             --------  --------
                                                    Total:     3.307     36.46

================================================================================
|     Voltage Constraints                                                      |
================================================================================
Bus #  Vmin mu    Vmin    |V|   Vmax    Vmax mu
-----  --------   -----  -----  -----   --------
    1      -      0.900  1.100  1.100     8.384
    6      -      0.900  1.100  1.100    75.329
    8      -      0.900  1.100  1.100    77.457
warning: struct: converting a classdef object into a struct overrides the access restrictions defined for properties. All properties are returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: struct: converting a classdef object into a struct overrides the access restrictions defined for properties. All properties are returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: struct: converting a classdef object into a struct overrides the access restrictions defined for properties. All properties are returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: struct: converting a classdef object into a struct overrides the access restrictions defined for properties. All properties are returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: save: wrong type argument 'function handle'
warning: called from
    _pyeval at line 97 column 3

---------------------------------------------------------------------------
Oct2PyError                               Traceback (most recent call last)
Input In [23], in <cell line: 3>()
      1 mpc = matpower.eval('case9', verbose=False)
----> 3 mpc = matpower.runopf(mpc)
      4 final = mpc.f

File ~\anaconda3\envs\work\lib\site-packages\oct2py\dynamic.py:103, in OctaveFunctionPtr.__call__(self, *inputs, **kwargs)
     97     warnings.warn('Key - value pairs are deprecated, use `func_args`',
     98                   stacklevel=2)
    100 inputs += tuple(item for pair in zip(extras.keys(), extras.values())
    101                 for item in pair)
--> 103 return self._ref().feval(self.name, *inputs, **kwargs)

File ~\anaconda3\envs\work\lib\site-packages\oct2py\core.py:392, in Oct2Py.feval(self, func_path, *func_args, **kwargs)
    389 if not stream_handler:
    390     stream_handler = self.logger.info if verbose else self.logger.debug
--> 392 return self._feval(func_name, func_args, dname=dname, nout=nout,
    393                   timeout=timeout, stream_handler=stream_handler,
    394                   store_as=store_as, plot_dir=plot_dir)

File ~\anaconda3\envs\work\lib\site-packages\oct2py\core.py:595, in Oct2Py._feval(self, func_name, func_args, dname, nout, timeout, stream_handler, store_as, plot_dir)
    593 if resp['err']:
    594     msg = self._parse_error(resp['err'])
--> 595     raise Oct2PyError(msg)
    597 result = resp['result'].ravel().tolist()
    598 if isinstance(result, list) and len(result) == 1:

Oct2PyError: Octave evaluation error:
error: save: error while writing '' to MAT file
```

**Comment by yasirroni** [comment]
Please read [README.md](https://github.com/yasirroni/matpower-pip#extra-require-oct2py-or-matlabengine) on how to run opf.

**Comment by chiru7187** [comment]
for *runpf** case* ..*results are coming*.

But for *runopf case*..forllowing coming.

 OSQP Error!

MATPOWER Version 7.1, 08-Oct-2020 -- AC Optimal Power Flow
  AC OPF formulation: polar voltages, power balance eqns
MATPOWER Interior Point Solver -- MIPS, Version 1.4, 08-Oct-2020
 (using built-in linear solver)
Converged!

Converged in 0.20 seconds
Objective Function Value = 5296.69 $/hr
================================================================================
|     System Summary                                                           |
================================================================================

How many?                How much?              P (MW)            Q (MVAr)
---------------------    -------------------  -------------  -----------------
Buses              9     Total Gen Capacity     820.0        -900.0 to 900.0
Generators         3     On-line Capacity       820.0        -900.0 to 900.0
Committed Gens     3     Generation (actual)    318.3              -9.6
Loads              3     Load                   315.0             115.0
  Fixed            3       Fixed                315.0             115.0
  Dispatchable     0       Dispatchable          -0.0 of -0.0      -0.0
Shunts             0     Shunt (inj)             -0.0               0.0
Branches           9     Losses (I^2 * Z)         3.31             36.46
Transformers       0     Branch Charging (inj)     -              161.1
Inter-ties         0     Total Inter-tie Flow     0.0               0.0
Areas              1

                          Minimum                      Maximum
                 -------------------------  --------------------------------
Voltage Magnitude   1.072 p.u. @ bus 9          1.100 p.u. @ bus 8
Voltage Angle      -4.62 deg   @ bus 9          4.89 deg   @ bus 2
P Losses (I^2*R)             -                  1.39 MW    @ line 8-9
Q Losses (I^2*X)             -                  9.36 MVAr  @ line 8-2
Lambda P           24.03 $/MWh @ bus 2         25.00 $/MWh @ bus 9
Lambda Q           -0.00 $/MWh @ bus 3          0.11 $/MWh @ bus 9

================================================================================
|     Bus Data                                                                 |
================================================================================
 Bus      Voltage          Generation             Load          Lambda($/MVA-hr)
  #   Mag(pu) Ang(deg)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)     P        Q
----- ------- --------  --------  --------  --------  --------  -------  -------
    1  1.100    0.000*    89.80     12.94       -         -      24.756     -
    2  1.097    4.893    134.32      0.05       -         -      24.035     -
    3  1.087    3.249     94.19    -22.62       -         -      24.076     -
    4  1.094   -2.463       -         -         -         -      24.756   0.004
    5  1.084   -3.982       -         -       90.00     30.00    24.998   0.027
    6  1.100    0.602       -         -         -         -      24.076     -
    7  1.089   -1.197       -         -      100.00     35.00    24.254   0.036
    8  1.100    0.905       -         -         -         -      24.035     -
    9  1.072   -4.616       -         -      125.00     50.00    24.999   0.112
                        --------  --------  --------  --------
               Total:    318.31     -9.63    315.00    115.00

================================================================================
|     Branch Data                                                              |
================================================================================
Brnch   From   To    From Bus Injection   To Bus Injection     Loss (I^2 * Z)
  #     Bus    Bus    P (MW)   Q (MVAr)   P (MW)   Q (MVAr)   P (MW)   Q (MVAr)
-----  -----  -----  --------  --------  --------  --------  --------  --------
   1      1      4     89.80     12.94    -89.80     -9.02     0.000      3.92
   2      4      5     35.22     -3.90    -35.04    -13.87     0.181      0.98
   3      5      6    -54.96    -16.13     55.97    -22.18     1.010      4.40
   4      3      6     94.19    -22.62    -94.19     27.28     0.000      4.66
   5      6      7     38.22     -5.10    -38.07    -18.68     0.149      1.26
   6      7      8    -61.93    -16.32     62.21      0.82     0.279      2.36
   7      8      2   -134.32      9.32    134.32      0.05     0.000      9.36
   8      8      9     72.11    -10.14    -70.72    -18.94     1.394      7.01
   9      9      4    -54.28    -31.06     54.58     12.92     0.295      2.51
                                                             --------  --------
                                                    Total:     3.307     36.46

================================================================================
|     Voltage Constraints                                                      |
================================================================================
Bus #  Vmin mu    Vmin    |V|   Vmax    Vmax mu
-----  --------   -----  -----  -----   --------
    1      -      0.900  1.100  1.100     8.384
    6      -      0.900  1.100  1.100    75.329
    8      -      0.900  1.100  1.100    77.457
warning: error caught while executing handle class delete method:
'osqp_mex' undefined near line 40, column 13
warning: struct: converting a classdef object into a struct overrides
the access restrictions defined for properties. All properties are
returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: struct: converting a classdef object into a struct overrides
the access restrictions defined for properties. All properties are
returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: struct: converting a classdef object into a struct overrides
the access restrictions defined for properties. All properties are
returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: struct: converting a classdef object into a struct overrides
the access restrictions defined for properties. All properties are
returned, including private and protected ones.
warning: called from
    _pyeval at line 97 column 3

warning: save: wrong type argument 'function handle'
warning: called from
    _pyeval at line 97 column 3


---------------------------------------------------------------------------Oct2PyError
                              Traceback (most recent call last)
Input In [6], in <cell line: 4>()      1 from matpower import
start_instance      3 m = start_instance()----> 4 m.runopf()

File ~\anaconda3\envs\work\lib\site-packages\oct2py\dynamic.py:103, in
OctaveFunctionPtr.__call__(self, *inputs, **kwargs)     97
warnings.warn('Key - value pairs are deprecated, use `func_args`',
98                   stacklevel=2)    100 inputs += tuple(item for
pair in zip(extras.keys(), extras.values())    101                 for
item in pair)--> 103 return self._ref().feval(self.name, *inputs,
**kwargs)

File ~\anaconda3\envs\work\lib\site-packages\oct2py\core.py:392, in
Oct2Py.feval(self, func_path, *func_args, **kwargs)    389 if not
stream_handler:    390     stream_handler = self.logger.info if
verbose else self.logger.debug--> 392 return self._feval(func_name,
func_args, dname=dname, nout=nout,    393
timeout=timeout, stream_handler=stream_handler,    394
  store_as=store_as, plot_dir=plot_dir)

File ~\anaconda3\envs\work\lib\site-packages\oct2py\core.py:595, in
Oct2Py._feval(self, func_name, func_args, dname, nout, timeout,
stream_handler, store_as, plot_dir)    593 if resp['err']:    594
msg = self._parse_error(resp['err'])--> 595     raise Oct2PyError(msg)
   597 result = resp['result'].ravel().tolist()    598 if
isinstance(result, list) and len(result) == 1:
Oct2PyError: Octave evaluation error:
error: save: error while writing '' to MAT file




*Why Oct2pyerror coming ..how can i debug it..please help me*

**Comment by yasirroni** [comment]
Already answered in README.MD. Please read the tutorial until finished.

Don't parse back runopf object to Python.

**Comment by yasirroni** [comment]
```
# import start_instance to start matpower instance
from matpower import start_instance

# start instance
m = start_instance()

# use octave native to run some commands
m.eval("mpopt = mpoption('verbose', 2);")
m.eval("mpc = loadcase('case9');")
m.eval("r1 = runopf(mpc, mpopt);") # we avoid parse `r1` that containts unsupported `<object opf_model>`
```

**Comment by chiru7187** [comment]
Got it, thanks!

**Comment by chiru7187** [comment]
Why *Data for case9 bus system *is different in *Matlab MATPOWER 7.1* and
in the *python that one being called*.
 additional information in Bus data, different Gen data and additional
information in Branch data...why these differences in data ...Please
clarify it.

*Matlab MATPOWER 7.1*
mpc.bus = [
1 3 0 0 0 0 1 1 0 345 1 1.1 0.9;
2 2 0 0 0 0 1 1 0 345 1 1.1 0.9;
3 2 0 0 0 0 1 1 0 345 1 1.1 0.9;
4 1 0 0 0 0 1 1 0 345 1 1.1 0.9;
5 1 90 30 0 0 1 1 0 345 1 1.1 0.9;
6 1 0 0 0 0 1 1 0 345 1 1.1 0.9;
7 1 100 35 0 0 1 1 0 345 1 1.1 0.9;
8 1 0 0 0 0 1 1 0 345 1 1.1 0.9;
9 1 125 50 0 0 1 1 0 345 1 1.1 0.9;
];


*python that one being called*

 'bus': array([[ 1.00000000e+00,  3.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.09997460e+00,  0.00000000e+00,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.52498161e+01,  1.78268697e-08,
          9.03392869e+00,  0.00000000e+00],
        [ 2.00000000e+00,  2.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.09657454e+00,  3.62376496e+00,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.45720897e+01, -4.43195677e-09,
          0.00000000e+00,  0.00000000e+00],
        [ 3.00000000e+00,  2.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.08586698e+00,  3.46595862e+00,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.45312932e+01, -3.15050243e-08,
          0.00000000e+00,  0.00000000e+00],
        [ 4.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.09428034e+00, -2.52448478e+00,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.52500260e+01,  4.75046423e-03,
          0.00000000e+00,  0.00000000e+00],
        [ 5.00000000e+00,  1.00000000e+00,  9.00000000e+01,
          3.00000000e+01,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.08438824e+00, -3.96553411e+00,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.54905372e+01,  2.79384872e-02,
          0.00000000e+00,  0.00000000e+00],
        [ 6.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.09999936e+00,  7.65162819e-01,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.45312936e+01,  1.85658001e-06,
          8.55470106e+01,  0.00000000e+00],
        [ 7.00000000e+00,  1.00000000e+00,  8.00000000e+01,
          3.50000000e+01,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.09066282e+00, -1.04568786e+00,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.47196322e+01,  3.34284653e-02,
          0.00000000e+00,  0.00000000e+00],
        [ 8.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.09999908e+00,  3.56380643e-01,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.45720906e+01,  8.44330726e-06,
          5.97331226e+01,  0.00000000e+00],
        [ 9.00000000e+00,  1.00000000e+00,  1.25000000e+02,
          5.00000000e+01,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.07209231e+00, -4.84235556e+00,
          3.45000000e+02,  1.00000000e+00,  1.10000000e+00,
          9.00000000e-01,  2.55096395e+01,  1.12836518e-01,
          0.00000000e+00,  0.00000000e+00]]),

**Comment by yasirroni** [comment]
Please make separate issue and specify MATPOWER version using `matpower.__version__`>

Also please check the .m file from 'from matpower import path_matpower`.

**Comment by yasirroni** [comment]
@chiru7187 Maybe you are interested in https://github.com/yasirroni/matpower-pip/issues/8
