### ISSUE TITLE
regarding adding and deleting data to the test case

### ISSUE THREAD

**Issue by chiru7187** [yasirroni/matpower-pip#5]
I have gone through these things and understood ..how to modify data 

r1_mpc = {}
r1_mpc['baseMVA'] = m.eval('r1.baseMVA;')
r1_mpc['version'] = m.eval('r1.version;')
r1_mpc['bus'] = m.eval('r1.bus;')
r1_mpc['gen'] = m.eval('r1.gen;')
r1_mpc['branch'] = m.eval('r1.branch;')
r1_mpc['gencost'] = m.eval('r1.gencost;')

# modify variable if necessary
[GEN_BUS, PG, QG, QMAX, QMIN, VG, MBASE, GEN_STATUS, PMAX, PMIN, MU_PMAX, 
 MU_PMIN, MU_QMAX, MU_QMIN, PC1, PC2, QC1MIN, QC1MAX, QC2MIN, QC2MAX, 
 RAMP_AGC, RAMP_10, RAMP_30, RAMP_Q, APF] = m.idx_gen(nout='max_nout')
gen_index = 2 # index of generator to be changed
gen_index_ = int(gen_index - 1) # -1 due to python indexing start from 0
PMAX_ = int(PMAX -1) # -1 due to python indexing start from 0
r1_mpc['gen'][gen_index_,PMAX_] = 110 # in this example, we modify PMAX to be 110

[PQ, PV, REF, NONE, BUS_I, BUS_TYPE, PD, QD, GS, BS, 
 BUS_AREA, VM, VA, BASE_KV, ZONE, VMAX, VMIN, LAM_P, 
 LAM_Q, MU_VMAX, MU_VMIN] = m.idx_bus(nout='max_nout')
bus_index = 7 # index of bus to be changed
bus_index_ = int(bus_index - 1) # -1 due to python indexing start from 0
PD_ = int(PD-1) # -1 due to python indexing start from 0
r1_mpc['bus'][bus_index_,int(PD-1)] = 80 # in this example, we modify PD to be 150

# push back value to octave client
m.push('mpc', r1_mpc) # push r1_mpc in python to mpc in octave

# test if we can retrive pushed value
mpc = m.pull('mpc')

# test if our pushed variable can be used
m.eval("r1 = rundcopf(mpc, mpopt);"

**_But in a case where data of one row is to be added or one column to be added to the test system._** 
I will be thankful if you could share this information.

Thank you

**Comment by yasirroni** [comment]
Please read Oct2Py manual regarding data modification. If after you read Oct2Py manual you are still confused, feel free to ask here. If you find something useful, feel free to share it here for others.

**Comment by chiru7187** [comment]
I tried to understand but couldn't. Please explain me.

**Comment by chiru7187** [comment]
Could you please give an example where one row and one column of data for
case 9 were modified?
It will help me a lot..Thank you

**Comment by yasirroni** [comment]
Use `np.vstack` to add new row. See [notebook](https://github.com/yasirroni/matpower-pip/blob/master/notebooks/add_new_row.ipynb)

___
Don't forget to do proper citation on using matpower-pip.
https://github.com/yasirroni/matpower-pip#cite
