### ISSUE TITLE
EOF: End Of File (EOF).

### ISSUE THREAD

**Issue by chiru7187** [yasirroni/matpower-pip#7]
**After this code**
m = start_instance()

**following error occured**
---------------------------------------------------------------------------
EOF                                       Traceback (most recent call last)
<ipython-input-542-02967a4f91db> in <module>
----> 1 n = start_instance()

~\anaconda3\lib\site-packages\matpower\__init__.py in start_instance(path_matpower, engine, add_path, save_path)
     19     """
     20 
---> 21     m = start_session(engine=engine)
     22 
     23     if add_path:

~\anaconda3\lib\site-packages\matpower\__init__.py in start_session(engine)
     38         try:
     39             from oct2py import Oct2Py
---> 40             m = Oct2Py()
     41         except ImportError:
     42             msg = f"No package named Oct2Py. Please install using `pip install matpower[octave]` or `pip install oct2py`."

~\anaconda3\lib\site-packages\oct2py\core.py in __init__(self, logger, timeout, oned_as, temp_dir, convert_to_float, backend)
     81         self._user_classes = {}
     82         self._function_ptrs = {}
---> 83         self.restart()
     84 
     85     @property

~\anaconda3\lib\site-packages\oct2py\core.py in restart(self)
    531             os.environ['OCTAVE_EXECUTABLE'] = os.environ['OCTAVE']
    532 
--> 533         self._engine = OctaveEngine(stdin_handler=self._handle_stdin,
    534                                     logger=self.logger)
    535 

~\anaconda3\lib\site-packages\octave_kernel\kernel.py in __init__(self, error_handler, stream_handler, line_handler, stdin_handler, plot_settings, inline_toolkit, defer_startup, cli_options, logger)
    174         self.cli_options = cli_options
    175         self.inline_toolkit = inline_toolkit
--> 176         self.repl = self._create_repl()
    177         self.error_handler = error_handler
    178         self.stream_handler = stream_handler

~\anaconda3\lib\site-packages\octave_kernel\kernel.py in _create_repl(self)
    400         change_prompt = u("PS1('{0}'); PS2('{1}')")
    401 
--> 402         repl = REPLWrapper(cmd, orig_prompt, change_prompt,
    403                            stdin_prompt_regex=STDIN_PROMPT_REGEX,
    404                            force_prompt_on_continuation=True)

~\anaconda3\lib\site-packages\metakernel\replwrap.py in __init__(self, cmd_or_spawn, prompt_regex, prompt_change_cmd, new_prompt_regex, continuation_prompt_regex, stdin_prompt_regex, extra_init_cmd, prompt_emit_cmd, force_prompt_on_continuation, echo)
     86             self.prompt_change_cmd = None
     87         else:
---> 88             self.set_prompt(prompt_regex,
     89                             prompt_change_cmd.format(new_prompt_regex,
     90                                                      continuation_prompt_regex))

~\anaconda3\lib\site-packages\metakernel\replwrap.py in set_prompt(self, prompt_regex, prompt_change_cmd)
    110 
    111     def set_prompt(self, prompt_regex, prompt_change_cmd):
--> 112         self.child.expect(prompt_regex)
    113         self.sendline(prompt_change_cmd)
    114         self.prompt_change_cmd = prompt_change_cmd

~\anaconda3\lib\site-packages\pexpect\spawnbase.py in expect(self, pattern, timeout, searchwindowsize, async_, **kw)
    341 
    342         compiled_pattern_list = self.compile_pattern_list(pattern)
--> 343         return self.expect_list(compiled_pattern_list,
    344                 timeout, searchwindowsize, async_)
    345 

~\anaconda3\lib\site-packages\pexpect\spawnbase.py in expect_list(self, pattern_list, timeout, searchwindowsize, async_, **kw)
    370             return expect_async(exp, timeout)
    371         else:
--> 372             return exp.expect_loop(timeout)
    373 
    374     def expect_exact(self, pattern_list, timeout=-1, searchwindowsize=-1,

~\anaconda3\lib\site-packages\pexpect\expect.py in expect_loop(self, timeout)
    177                     timeout = end_time - time.time()
    178         except EOF as e:
--> 179             return self.eof(e)
    180         except TIMEOUT as e:
    181             return self.timeout(e)

~\anaconda3\lib\site-packages\pexpect\expect.py in eof(self, err)
    120             exc = EOF(msg)
    121             exc.__cause__ = None # in Python 3.x we can use "raise exc from None"
--> 122             raise exc
    123 
    124     def timeout(self, err=None):

EOF: End Of File (EOF).
<pexpect.popen_spawn.PopenSpawn object at 0x000001DCAF3FE8E0>
searcher: searcher_re:
    0: re.compile('octave.*>')

​

**Comment by yasirroni** [comment]
Please use code fence for code. You can edit your question, please. See it [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks) or [here](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks).

**Comment by yasirroni** [comment]
What OS did you use your code? EOF error is because you use different format for textfile compared to be with the one used by your OS.

I don't think that is caused by matpower-pip.

Maybe in anaconda, there is an auto formatter to change EOF based on current OS. If there is exist such feature, please use that feature. If there is no feature, try to stay away from anaconda and pycharm. Use VSCode and pip instead.

You can re-open if you can pin point that `matpower-pip` is the cause.

**Comment by chiru7187** [comment]
OS is WINDOWS

**Comment by chiru7187** [comment]
please help me in solving the issue.

**Comment by yasirroni** [comment]
@chiru7187 Can you also edit the error output so that it is readable using code fence too?

Please also write step by step installation process and running process. I don't have conda so I'm limited in giving any help.
